name: pytest_and_docs

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install poetry
      run: | 
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install firefox-geckodriver
        python -m pip install --upgrade pip
        poetry install
    - name: Test with pytest
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      run: |
        poetry run pytest --webdriver Firefox --headless crystal_toolkit/apps/examples/tests/
    - name: Build new docs
      run: |
        git config --global user.name 'Matthew Horton'
        git config --global user.email 'mkhorton@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        cd docs_rst
        poetry run make html
    - name: Commit new docs
      run: |
        git add -A
        git diff-index --quiet HEAD || git commit -m "Automated doc build"
        git push
      continue-on-error: true

