name: release

on:
  create:
    tags:
      - v*

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install firefox-geckodriver
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Set up git
      run: |
        git config --global user.name 'Matthew Horton'
        git config --global user.email 'mkhorton@users.noreply.github.com'
        git status
    - name: Set new version
      run: |
        cat package.json | jq '.version="'$(date '+%Y.%m.%d')'"' > package.json
        cat crystal_toolkit/package.json | jq '.version="'$(date '+%Y.%m.%d')'"' > crystal_toolkit/package.json
        git status
        git diff --quiet || git commit -am "Set version"
        git push
    - name: Build packages
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
