name: release

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calver Release
        uses: StephaneBour/actions-calver@v1.5
        id: calver
        with:
          date_format: "%Y.%m.%d"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: '**/pyproject.toml'

      - name: Install dependencies
        run: |
          python${{ matrix.python-version }} -m pip install --upgrade pip pip-tools build setuptools setuptools_scm wheel numpy
          python${{ matrix.python-version }} -m piptools sync --user requirements/ubuntu-latest_py${{ matrix.python-version }}_extras.txt
          python${{ matrix.python-version }} -m pip install --user --no-deps .[server]

      - name: Build package
        run: python${{ matrix.python-version }} -m build

      #- name: Publish package
      #  uses: pypa/gh-action-pypi-publish@release/v1.5
      #  with:
      #    user: __token__
      #    password: ${{ secrets.PYPI_API_TOKEN }}
