name: Check URLs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Check URL
        uses: urlstechie/urlchecker-action@master
        with:
          file_types: .md,.py,.rst  # file types to check URLs in
          timeout: 5  # allowed timeout for requests to resolve, default = 5 sec
          retry_count: 2
