name: Check URLs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lychee-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1
        with:
          # exclude loopback to skip localhost URLs from checking
          args: --exclude-loopback './**/*.md' './**/*.rst'
